@startuml
class Path {
    + Path()
    + Path(path:string)
    + <<override>> Edit(input:string) : void
    + <<override>> ToString() : string
    + <<override>> ToSvgString() : string
}
Shape <|-- Path
@enduml
