@startuml
class Point <<sealed>> {
    {static} id : int
    X : string <<get>> <<set>>
    Y : string <<get>> <<set>>
    + Point(X:string, Y:string)
    + <<override>> ToString() : string
}
@enduml
