@startuml
class Style {
    + Style()
    + EditProperty(key:string, value:string) : void
    + RemoveStyle(key:string) : void
    + ShowStyles() : string
    + <<override>> ToString() : string
    + ToSvgString() : string
}
@enduml
